<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLEN8Vna\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLEN8Vna/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLEN8Vna.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLEN8Vna\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLEN8Vna\App_KernelDevDebugContainer([
    'container.build_hash' => 'LEN8Vna',
    'container.build_id' => 'dd269819',
    'container.build_time' => 1721171692,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLEN8Vna');
