<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ccx4ZJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ccx4ZJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0ccx4ZJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0ccx4ZJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0ccx4ZJ\App_KernelDevDebugContainer([
    'container.build_hash' => '0ccx4ZJ',
    'container.build_id' => '80e09795',
    'container.build_time' => 1720862526,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0ccx4ZJ');
