<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_contacts' => [[], ['_controller' => 'App\\Controller\\ContactsController::index'], [], [['text', '/contacts']], [], [], []],
    'app_history' => [[], ['_controller' => 'App\\Controller\\HistoryController::index'], [], [['text', '/history']], [], [], []],
    'app_index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/index']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'settings_api_keys_delete' => [['id'], ['_controller' => 'App\\Controller\\SettingsController::deleteApiKey'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/settings/api-key/delete']], [], [], []],
    'receive' => [[], ['_controller' => 'App\\Controller\\PaymentController::receive'], [], [['text', '/receive']], [], [], []],
    'pay' => [[], ['_controller' => 'App\\Controller\\PaymentController::pay'], [], [['text', '/pay']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], [], []],
    'history' => [[], ['_controller' => 'App\\Controller\\HistoryController::history'], [], [['text', '/history']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Security\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Security\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_settings' => [[], ['_controller' => 'App\\Controller\\SettingsController::index'], [], [['text', '/settings']], [], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_contact' => [[], ['_controller' => 'App\\Controller\\ContactsController::contacts'], [], [['text', '/contacts']], [], [], []],
    'api_index' => [[], ['_controller' => 'App\\Security\\APIController::index'], [], [['text', '/api']], [], [], []],
    'App\Controller\APIController::getConfig' => [[], ['_controller' => 'App\\Security\\APIController::index'], [], [['text', '/api']], [], [], []],
    'App\Controller\ContactsController::index' => [[], ['_controller' => 'App\\Controller\\ContactsController::index'], [], [['text', '/contacts']], [], [], []],
    'App\Controller\HistoryController::index' => [[], ['_controller' => 'App\\Controller\\HistoryController::index'], [], [['text', '/history']], [], [], []],
    'App\Controller\IndexController::index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/index']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\SettingsController::index' => [[], ['_controller' => 'App\\Controller\\SettingsController::index'], [], [['text', '/settings']], [], [], []],
    'App\Controller\SettingsController::deleteApiKey' => [['id'], ['_controller' => 'App\\Controller\\SettingsController::deleteApiKey'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/settings/api-key/delete']], [], [], []],
];
