<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_history' => [[], ['_controller' => 'App\\Controller\\HistoryController::index'], [], [['text', '/history']], [], [], []],
    'app_index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/index']], [], [], []],
    'create_invoice' => [[], ['_controller' => 'App\\Controller\\PaymentController::create_invoice'], [], [['text', '/create_invoice']], [], [], []],
    'pay_invoice' => [[], ['_controller' => 'App\\Controller\\PaymentController::pay_invoice'], [], [['text', '/pay_invoice']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], [], []],
    'history' => [[], ['_controller' => 'App\\Controller\\HistoryController::history'], [], [['text', '/history']], [], [], []],
    'App\Controller\HistoryController::index' => [[], ['_controller' => 'App\\Controller\\HistoryController::index'], [], [['text', '/history']], [], [], []],
    'App\Controller\IndexController::index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/index']], [], [], []],
];
